### PR TITLE
Adds docker support #117

### PR DESCRIPTION
**Pull request by nlocnila**
Here's a working copy of this image: `docker pull nlocnila/wzrd.in`
Run the following: `$ docker run -p 8080:8080 nlocnila/wzrd.in`

I wasn't sure if the maintainer wanted to build his own image and host it so I didn't fill out the MAINTAINER field or add instructions on the README. I'll add another follow-up PR if needed.

### CODE REVIEW

**Comment by jfhbrook** [comment]
Sorry, I was on vacation.

So this just adds a Dockerfile? I'm not particularly interested in changing the ops side of how wzrd.in works (what we have now, well, *works*), but I could see this being useful for other people, and even in the future more generally.

**Comment by nlocnila** [comment]
Yeah the idea is that people can create an image (or pull one from the docker hub) and run their own isolated instance, this isn't intended to change anything of what works right now

**Comment by jfhbrook** [comment]
Okay, so yeah, idk about the MAINTAINER field but I don't really want to be taking responsibility here so maybe leaving it blank is best?

**Comment by jfhbrook** [comment]
As far as the README, it would be entirely appropriate to write up a little blurb underneath the "heroku" directions.

Thanks!

**Comment by nlocnila** [comment]
Alright so I added two simple commands to get up and running. Whenever you decide to push this to docker hub and host your own official image, simply just add the MAINTAINER field (respecting best practices) and change the instructions to where people can pull the image like I did in the first comment. Cheers.

**Comment by jfhbrook** [comment]
Thanks!

**Pull request merged**
